version: '3.1'
services:
  stats-server:
    build:
      context: stat/server
      dockerfile: Dockerfile_stat
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=imroot

  ewm-service:
    build:
      context: main
      dockerfile: Dockerfile_main
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6545:5432"
    environment:
      - POSTGRES_DB=ewm-main
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=imroot


