version: '3.1'
services:
  stats-server:
    build:
      context: ewm-statistics
      dockerfile: Dockerfile-ewm-statistics
    container_name: ewm-statistics
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats-server

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats-server
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=imroot

  ewm-service:
    build:
      context: ewm-service
      dockerfile: Dockerfile-ewm-service
    container_name: evm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db

  ewm-db:
    image: postgres:14-alpine
    ports:
      - "6545:5435"
    environment:
     - POSTGRES_DB=ewm-statistics-server
     - POSTGRES_USER=sa
     - POSTGRES_PASSWORD=imroot



